-- Generated by pipeline_data.schema_generate.
-- Vera initial schema.
-- halfvec(4096) = full Qwen3-8B width at 16-bit storage.
-- ! No ANN index on embedding: pgvector cannot index 4096 dims. Routing prunes, not an index.
-- chunks is partitioned by HASH(cluster_id) for the sequential per-cluster scan (OOM guarantee).
-- Provenance is captured at ingest and NOT NULL: the engine never synthesizes a citation.

CREATE EXTENSION IF NOT EXISTS vector;

-- Layer 1. anchor is the pre-embedded domain centroid matched against the query vector.
-- ! The agent never passes a domain; below-threshold means no match, not a guess.
CREATE TABLE domains (
    id TEXT PRIMARY KEY,
    description TEXT NOT NULL,
    anchor halfvec(4096) NOT NULL,
    row_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Layer 2. k-means centroids, the coarse quantizer. Held hot in engine memory;
-- this table is the durable copy. generation supports atomic re-cluster swaps.
CREATE TABLE clusters (
    id INTEGER PRIMARY KEY,
    domain_id TEXT NOT NULL REFERENCES domains(id) ON DELETE CASCADE,
    centroid halfvec(4096) NOT NULL,
    row_count BIGINT NOT NULL DEFAULT 0,
    generation INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX clusters_domain_idx ON clusters (domain_id, generation);

-- Layer 3. ! HASH partitioning, not LIST: ~10K clusters would mean ~10K partitions,
-- far past where the planner degrades. HASH gives locality at a fixed partition count.
CREATE TABLE chunks (
    id TEXT NOT NULL,
    domain_id TEXT NOT NULL,
    cluster_id INTEGER NOT NULL,
    body TEXT NOT NULL,
    embedding halfvec(4096) NOT NULL,
    source_title TEXT NOT NULL,
    source_url TEXT NOT NULL,
    locator_page INTEGER,
    locator_section TEXT,
    heading_path TEXT,
    identifier TEXT,
    tsv tsvector GENERATED ALWAYS AS (to_tsvector('simple', body)) STORED,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (cluster_id, id)
) PARTITION BY HASH (cluster_id);

DO $$
BEGIN
    FOR i IN 0..63 LOOP
        EXECUTE format('CREATE TABLE chunks_p%s PARTITION OF chunks FOR VALUES WITH (MODULUS 64, REMAINDER %s)', i, i);
    END LOOP;
END $$;
CREATE INDEX chunks_cluster_idx ON chunks (cluster_id);
CREATE INDEX chunks_tsv_idx ON chunks USING GIN (tsv);
CREATE INDEX chunks_identifier_idx ON chunks (identifier) WHERE identifier IS NOT NULL;

